# this variable must be setted
ZM_HOME=${HOME}/.local/share/zm
source ${ZM_HOME}/zm.zsh 2> /dev/null || {
    mkdir -p $(dirname $ZM_HOME)
    git clone https://github.com/nueks/zm $ZM_HOME
    source ${ZM_HOME}/zm.zsh
}
zm.load romkatv/zsh-defer

zm.load ohmyzsh/ohmyzsh plugins/magic-enter
zm.load ohmyzsh/ohmyzsh plugins/histroy-substring-search
zm.load ohmyzsh/ohmyzsh plugins/z

zm.load zpm-zsh/colorize

zm.load zpm-zsh/ls
export TIME_STYLE=iso

zm.load zsh-users/zsh-completions

zm.load zsh-users/zsh-history-substring-search

zm.load zsh-users/zsh-autosuggestions
ZSH_AUTOSUGGEST_USE_ASYNC=true
ZSH_AUTOSUGGEST_MANUAL_REBIND=1
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=250'

zm.load zsh-users/zsh-syntax-highlighting
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)
typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[comment]='fg=242'
ZSH_HIGHLIGHT_STYLES[path]=none
ZSH_HIGHLIGHT_STYLES[path_prefix]=none
unset "FAST_HIGHLIGHT[chroma-awk]"

zm.load agkozak/zsh-z
